# Session autostart apps
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = hyprpaper -c ~/.config/hypr/hyprpaper.conf
exec-once = waybar -c ~/.config/waybar/config.jsonc -s ~/.config/waybar/style.css
exec-once = mako
exec-once = blueman-applet
exec-once = nm-applet
exec-once = hyprpolkitagent
exec-once = eww daemon
